// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrygoN4ogbvEux7FFwrTsLte3RqVBeSi4',
    appId: '1:408329046304:web:3d3feaa24503982ca66f45',
    messagingSenderId: '408329046304',
    projectId: 'tokoroti-ae2ec',
    authDomain: 'tokoroti-ae2ec.firebaseapp.com',
    storageBucket: 'tokoroti-ae2ec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLim6-fhaGpX63eJZOWMF3wP6mTIAkIOA',
    appId: '1:408329046304:android:37b07c2909dbe7cda66f45',
    messagingSenderId: '408329046304',
    projectId: 'tokoroti-ae2ec',
    storageBucket: 'tokoroti-ae2ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIMsqEgyxzDn4SuWTmvbd7y1hl2k-SmoA',
    appId: '1:408329046304:ios:4bb64e4ebdbf12e5a66f45',
    messagingSenderId: '408329046304',
    projectId: 'tokoroti-ae2ec',
    storageBucket: 'tokoroti-ae2ec.appspot.com',
    iosBundleId: 'com.example.tokoRoti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIMsqEgyxzDn4SuWTmvbd7y1hl2k-SmoA',
    appId: '1:408329046304:ios:4bb64e4ebdbf12e5a66f45',
    messagingSenderId: '408329046304',
    projectId: 'tokoroti-ae2ec',
    storageBucket: 'tokoroti-ae2ec.appspot.com',
    iosBundleId: 'com.example.tokoRoti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrygoN4ogbvEux7FFwrTsLte3RqVBeSi4',
    appId: '1:408329046304:web:db0d47aa080cf3eea66f45',
    messagingSenderId: '408329046304',
    projectId: 'tokoroti-ae2ec',
    authDomain: 'tokoroti-ae2ec.firebaseapp.com',
    storageBucket: 'tokoroti-ae2ec.appspot.com',
  );
}
